spring.application.name=venue-service
server.port=8082

eureka.client.service-url.defaultZone=${EUREKA_SERVER_URL:http://localhost:8761/eureka}
eureka.instance.hostname=localhost
eureka.instance.prefer-ip-address=true
eureka.instance.ip-address=127.0.0.1

spring.datasource.url=${VENUE_DB_URL:jdbc:postgresql://localhost:5432/fairplay_venue_db}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=${VENUE_DB_USERNAME:postgres}
spring.datasource.password=${VENUE_DB_PASSWORD:HARIk@723506}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

server.error.include-message=always

security.jwt.secret=${JWT_SECRET:fairplay-secret-key-must-be-at-least-32-chars}
security.jwt.expiration-ms=${JWT_EXPIRATION_MS:3600000}