FROM maven:3.9.9-eclipse-temurin-21 AS build
WORKDIR /app

COPY . .
RUN chmod +x mvnw && ./mvnw -pl venue-service -am clean package -DskipTests

FROM eclipse-temurin:21-jre-jammy
WORKDIR /app

COPY --from=build /app/venue-service/target/venue-service-0.0.1-SNAPSHOT.jar app.jar

EXPOSE 8082
CMD ["java", "-jar", "app.jar"]
