spring.application.name=api-gateway
server.port=${PORT:8083}

eureka.client.enabled=${EUREKA_ENABLED:true}
spring.cloud.discovery.enabled=${EUREKA_ENABLED:true}
eureka.client.service-url.defaultZone=${EUREKA_SERVER_URL:http://${EUREKA_SERVER_HOST:localhost}:${EUREKA_SERVER_PORT:8761}/eureka}
eureka.instance.hostname=${EUREKA_INSTANCE_HOSTNAME:${RENDER_EXTERNAL_HOSTNAME:${RENDER_DISCOVERY_SERVICE:${HOSTNAME:localhost}}}}
eureka.instance.prefer-ip-address=false
eureka.instance.non-secure-port=${PORT:8083}

spring.cloud.gateway.routes[0].id=user-service
spring.cloud.gateway.routes[0].uri=${USER_SERVICE_URL:lb://user-service}
spring.cloud.gateway.routes[0].predicates[0]=Path=/users/**,/activities/**

spring.cloud.gateway.routes[1].id=venue-service
spring.cloud.gateway.routes[1].uri=${VENUE_SERVICE_URL:lb://venue-service}
spring.cloud.gateway.routes[1].predicates[0]=Path=/venues/**,/bookings/**,/owners/**
